"use client";
import Header from "@/components/Header";
import Image from "next/image";
import "./index.scss";
import { Button, Collapse, theme } from "antd";
import { CaretRightOutlined } from "@ant-design/icons";
import { useState } from "react";
import Footer from "@/components/Footer";

export default function Home() {
  const qa = [
    {
      q: "How do Trees work?",
      a: 'Trees is a protocol chain that allows market participants to publish pricing information for others to use. The agreement is a three-party interaction:The data provider submits the pricing information to a Pyth oracle program. Trees provides multiple data providers for each price feed to increase the accuracy and robustness of the system.Trees’ on-chain oracle program on Solana combines provider submission data to produce a single total price and confidence interval.The application reads the price information generated by the oracle. More specifically, Trees allow users to "pull" prices onto the blockchain when needed. These prices are public and available to everyone on the chain.',
    },
    {
      q: 'What is an on-demand or " pull-based" oracle?',
      a: 'Trees is a protocol chain that allows market participants to publish pricing information for others to use. The agreement is a three-party interaction:The data provider submits the pricing information to a Pyth oracle program. Trees provides multiple data providers for each price feed to increase the accuracy and robustness of the system.Trees’ on-chain oracle program on Solana combines provider submission data to produce a single total price and confidence interval.The application reads the price information generated by the oracle. More specifically, Trees allow users to "pull" prices onto the blockchain when needed. These prices are public and available to everyone on the chain.',
    },
    {
      q: "How does Trees use Wormhole?",
      a: 'Trees is a protocol chain that allows market participants to publish pricing information for others to use. The agreement is a three-party interaction:The data provider submits the pricing information to a Pyth oracle program. Trees provides multiple data providers for each price feed to increase the accuracy and robustness of the system.Trees’ on-chain oracle program on Solana combines provider submission data to produce a single total price and confidence interval.The application reads the price information generated by the oracle. More specifically, Trees allow users to "pull" prices onto the blockchain when needed. These prices are public and available to everyone on the chain.',
    },
    {
      q: "What is the cost structure of using Trees Price Feeds?",
      a: 'Trees is a protocol chain that allows market participants to publish pricing information for others to use. The agreement is a three-party interaction:The data provider submits the pricing information to a Pyth oracle program. Trees provides multiple data providers for each price feed to increase the accuracy and robustness of the system.Trees’ on-chain oracle program on Solana combines provider submission data to produce a single total price and confidence interval.The application reads the price information generated by the oracle. More specifically, Trees allow users to "pull" prices onto the blockchain when needed. These prices are public and available to everyone on the chain.',
    },
  ];
  const [activeKeys, setActiveKeys] = useState<number[]>([]);

  return (
    <div className="home">
      <Header />
      <Image
        src="/images/l-bg.png"
        alt="Logo"
        className="absolute g-circle"
        width={600}
        height={600}
        priority
      />
      <div className="m-auto t-content flex flex-row items-center relative">
        <div className="flex flex-col items-start justify-center		">
          <div className="flex flex-row items-baseline relative">
            <p className="text-[#00FF0A] text-8xl">Trees Protocol</p>
            <p className="text-[#fff] text-6xl ml-10px">Powered by Solana</p>
            <Image
              src="/images/g-cir.png"
              alt="Logo"
              className="absolute g-c"
              width={200}
              height={200}
              priority
            />
          </div>
          <p className="text-[#fff] text-6xl leading-relaxed">
            Seed Inscription
          </p>
          <div className="flex flex-row mt-10px">
            <Button
              className="bg-[#fff] text-[#131313] mr-24px text-lg leading-5"
            >
              Mint
            </Button>
            <Button
              className="bg-[#05EB00] text-[#131313] text-lg leading-5"
              type="primary"
            >
              Get Reward
            </Button>
          </div>
        </div>

        <Image
          src="/images/tAnimation.png"
          alt="Logo"
          className="t-a"
          width={484}
          height={489}
          priority
        />
        <div className="g-c-r absolute flex items-center justify-center">
          <Image
            src="/images/g-cir-a.png"
            alt="g-c"
            width={16}
            height={129}
            priority
          />
        </div>
        {/* <Image
          src="/images/g-cir.png"
          alt="Logo"
          className="absolute g-c-r"
          width={336}
          height={336}
          priority
        /> */}
      </div>
      <div className="inf relative m-auto flex flex-col items-center">
        <Image
          src="/images/b.png"
          alt="inf"
          className="absolute inset-x-0px top-0px z-0"
          width={1920}
          height={305}
          priority
        />
        <p className="m-auto text-[#00FF0A] text-center text-5xl relative">
          Trees Protocal
        </p>
        <p className="m-auto text-left w-1100px relative mt-48px text-xl">
          Trees aims to create a special digital asset liquidity and transaction
          cost optimization platform based on Solana, providing users with an
          efficient, low-cost, and easy-to-use full chain digital asset
          management and trading environment，By introducing diversified Mint
          mechanisms to change the asset distribution methods of special digital
          asset markets, Trees provides unprecedented flexibility and innovative
          space for deployers of special assets.
        </p>
        <Button
          className="bg-[#05EB00] text-[#131313] m-auto mt-48px text-lg leading-5"
          type="primary"
        >
          Read Whitepaper
        </Button>
        <div className="m-auto locl relative mt-48px flex flex-row items-center justify-between pt-48px">
          <Image
            src="/images/cBg.png"
            alt="inf"
            className="absolute top-0px"
            width={1099}
            height={602}
            priority
          />
          {[1, 1, 1].map((_, i) => (
            <div key={i} className="flex items-center justify-center locl-op-c">
              <div className={`relative z-10 cursor-pointer locl-op-${i}`} />
            </div>
          ))}
        </div>
      </div>
      <div className="table-i flex flex-row relative m-auto items-end justify-between">
        <Image
          src="/images/l-bg.png"
          alt="l-bg"
          className="absolute g-circle-t"
          width={1000}
          height={1000}
          priority
        />
        <div className="l relative">
          <p className="text-[#00FF0A] text-2xl leading-relaxed mb-10px text-5xl">
            MINT Rules
          </p>
          <p className="text-[#fff] leading-relaxed text-xl">
            Trees Protocol Inscription Public Chain: Solana
          </p>
          <p className="text-[#fff] leading-relaxed text-xl">
            Trees Protocol Inscription Name: Seed
          </p>
          <p className="text-[#fff] leading-relaxed text-xl">
            Total number of inscriptions: 40000 (1905 are rewards distributed by
            the invite)
          </p>
          <p className="text-[#fff] leading-relaxed text-xl">
            Single sheet: 10000 tokens
          </p>
          <p className="text-[#fff] leading-relaxed text-xl">
            Single Mint fee: 0.1sol+sol real-time gas fee
          </p>
          <Image
            src="/images/rulers-line.png"
            alt="rulers-line"
            className="absolute rulers-line"
            width={702}
            height={72}
            priority
          />
          <Image
            src="/images/rulers-i.png"
            alt="rulers-i"
            className="absolute rulers-i"
            width={246}
            height={277}
            priority
          />
        </div>
        <div className="r relative">
          <p className="text-[#00FF0A] text-2xl leading-relaxed mb-10px text-5xl text-right">
            MINT Rules
          </p>
          <p className="text-[#fff] leading-relaxed text-xl text-right">
            lnvite reward:
          </p>
          <p className="text-[#fff] leading-relaxed text-xl text-right">
            Each successful invitation to a new user can earn 1 point.Obtain
            different levels
          </p>
          <p className="text-[#fff] leading-relaxed text-xl text-right">
            of seed lnscription rewards based on the total pointsearned
          </p>
          <Image
            src="/images/rulers-line1.png"
            alt="rulers-line1"
            className="absolute rulers-line1"
            width={700}
            height={99}
            priority
          />
          <Image
            src="/images/rulers1-bg.png"
            alt="rulers1-bg"
            className="absolute rulers1-bg"
            width={602}
            height={216}
            priority
          />
        </div>
      </div>
      <div className="qa m-auto mt-48px">
        <div className="flex flex-row items-center justify-center text-[#00FF0A] text-5xl mb-48px">
          Q
          <Image
            src="/images/g-icon.png"
            alt="g-icon"
            width={32}
            height={54}
            priority
          />
          A
        </div>
        {qa.map((e, i) => {
          const isActive = activeKeys.includes(i);
          return (
            <div
              key={e.q}
              className={`qa-i p-24px mb-48px ${isActive ? "ac" : "deac"}`}
            >
              <p className="qa-q flex flex-row items-center justify-between h-48px">
                <span
                  className={`${
                    isActive ? "text-[#00FF0A]" : "text-[#fff]"
                  } text-2xl`}
                >
                  {e.q}
                </span>
                <Image
                  src={`/images/${!isActive ? "open" : "closed"}.png`}
                  alt=""
                  width={30}
                  height={30}
                  priority
                  className="cursor-pointer"
                  onClick={() => {
                    if (isActive) {
                      setActiveKeys(activeKeys.filter((k) => k !== i));
                    } else {
                      setActiveKeys([...activeKeys, i]);
                    }
                  }}
                />
              </p>
              <p
                className={`qa-a pt-24px text-xl ${
                  isActive ? "open" : "closed"
                }`}
              >
                {e.a}
              </p>
            </div>
          );
        })}
      </div>
      <Footer />
    </div>
  );
}
