"use client";
import Header from "@/components/Header";
import Image from "next/image";
import "./index.scss";
import { Button, Collapse, theme } from "antd";
import { CaretRightOutlined } from "@ant-design/icons";
import { useState } from "react";
import Footer from "@/components/Footer";

export default function Reward() {
  const qa = [
    {
      q: "How do Trees work?",
      a: 'Trees is a protocol chain that allows market participants to publish pricing information for others to use. The agreement is a three-party interaction:The data provider submits the pricing information to a Pyth oracle program. Trees provides multiple data providers for each price feed to increase the accuracy and robustness of the system.Trees’ on-chain oracle program on Solana combines provider submission data to produce a single total price and confidence interval.The application reads the price information generated by the oracle. More specifically, Trees allow users to "pull" prices onto the blockchain when needed. These prices are public and available to everyone on the chain.',
    },
    {
      q: 'What is an on-demand or " pull-based" oracle?',
      a: 'Trees is a protocol chain that allows market participants to publish pricing information for others to use. The agreement is a three-party interaction:The data provider submits the pricing information to a Pyth oracle program. Trees provides multiple data providers for each price feed to increase the accuracy and robustness of the system.Trees’ on-chain oracle program on Solana combines provider submission data to produce a single total price and confidence interval.The application reads the price information generated by the oracle. More specifically, Trees allow users to "pull" prices onto the blockchain when needed. These prices are public and available to everyone on the chain.',
    },
    {
      q: "How does Trees use Wormhole?",
      a: 'Trees is a protocol chain that allows market participants to publish pricing information for others to use. The agreement is a three-party interaction:The data provider submits the pricing information to a Pyth oracle program. Trees provides multiple data providers for each price feed to increase the accuracy and robustness of the system.Trees’ on-chain oracle program on Solana combines provider submission data to produce a single total price and confidence interval.The application reads the price information generated by the oracle. More specifically, Trees allow users to "pull" prices onto the blockchain when needed. These prices are public and available to everyone on the chain.',
    },
    {
      q: "What is the cost structure of using Trees Price Feeds?",
      a: 'Trees is a protocol chain that allows market participants to publish pricing information for others to use. The agreement is a three-party interaction:The data provider submits the pricing information to a Pyth oracle program. Trees provides multiple data providers for each price feed to increase the accuracy and robustness of the system.Trees’ on-chain oracle program on Solana combines provider submission data to produce a single total price and confidence interval.The application reads the price information generated by the oracle. More specifically, Trees allow users to "pull" prices onto the blockchain when needed. These prices are public and available to everyone on the chain.',
    },
  ];
  const [activeKeys, setActiveKeys] = useState<number[]>([]);
  return (
    <div className="reward">
      <Header />
      <Image
        src="/images/l-bg.png"
        alt="Logo"
        className="absolute g-circle"
        width={600}
        height={600}
        priority
        quality={100}
      />
      <div className="m-auto t-content flex flex-row items-center justify-between relative">
        <div className="flex flex-col items-start justify-center		">
          <div className="flex flex-row items-baseline relative">
            <p className="text-[#fff] text-8xl">SEED Inscription</p>
            <Image
              src="/images/g-cir.png"
              alt="Logo"
              className="absolute g-c"
              width={75}
              height={75}
              priority
              quality={100}
            />
          </div>
          <p className="text-[#00FF0A] text-8xl">Invitation Reward</p>
          <p className="text-[#fff] text-3xl leading-relaxed">
            Invite friends to earn more Trees XP
          </p>
          <div className="flex flex-row mt-10px">
            <Button
              className="bg-[#fff] text-[#131313] mr-24px text-lg leading-5"
              size="large"
            >
              <div className="flex items-center text-2xl leading-5">
                <Image
                  src="/images/x.png"
                  alt=""
                  width={18}
                  height={18}
                  className="mr-10px"
                  priority
                  quality={100}
                />
                Share on Twitter
              </div>
            </Button>
            <Button
              className="bg-[#fff] text-[#131313] text-lg leading-5"
              size="large"
            >
              <div className="flex items-center text-2xl leading-5">
                <Image
                  src="/images/t.png"
                  alt=""
                  width={18}
                  height={18}
                  className="mr-10px"
                  priority
                  quality={100}
                />
                Share on Telegram
              </div>
            </Button>
          </div>
        </div>

        <div className="hr relative p-24px flex flex-col">
          <Image
            src="/images/l-bg.png"
            alt="Logo"
            className="absolute hr-g-circle"
            width={150}
            height={150}
            priority
            quality={100}
          />
          <Image
            src="/images/l-bg.png"
            alt="Logo"
            className="absolute hr-g-rward-circle"
            width={250}
            height={250}
            priority
            quality={100}
          />
          <Image
            src="/images/rward-tm.png"
            alt="Logo"
            className="absolute hr-rward-tm"
            width={150}
            height={150}
            priority
            quality={100}
          />
          <p className="flex-1 text-5xl text-[#00FF0A] hr-line">My trees</p>
          <p className="flex-1 text-5xl text-[#00FF0A] text-right flex flex-col justify-end">
            <span>1000</span>
          </p>
        </div>
      </div>
      <div className="flex items-center justify-center text-3xl">
        My invitation code: 4234234234{" "}
        <Image
          src="/images/copy.png"
          alt="Logo"
          className="ml-10px cursor-pointer"
          width={24}
          height={24}
          priority
          quality={100}
        />
      </div>
      <div className="inf relative m-auto flex flex-col items-center">
        <Image
          src="/images/b.png"
          alt="inf"
          className="absolute inset-x-0px top-0px z-0"
          width={1920}
          height={305}
          priority
          quality={100}
        />
        <Image
          src="/images/l-bg.png"
          alt="l-bg"
          className="absolute g-circle-t"
          width={800}
          height={800}
          priority
          quality={100}
        />
        <div className="tables flex flex-row relative justify-between">
          <div className="ta-l flex-1">
            <p className="text-[#00FF0A] t-border t-h-text text-3xl">
              Reward System
            </p>
            <div className="t-body t-border">
              <p className="ti text-5xl text-center">My invitation</p>
              <div className="flex flex-row">
                {["user", "time"].map((e, i) => {
                  return (
                    <div key={i} className="flex-1 line">
                      {[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1].map((_, id) => {
                        return (
                          <p key={id} className="text-2xl text-center line-i">
                            {e}
                          </p>
                        );
                      })}
                    </div>
                  );
                })}
              </div>
              <p className="more text-center text-2xl">MORE ……</p>
            </div>
          </div>
          <div className="ta-r flex-1">
            <p className="text-[#00FF0A] t-border t-h-text text-3xl">
              Terms of participation
            </p>
            <div className="t-body t-border">
              <p className="ti text-5xl text-center">Leaderboard</p>
              <div className="flex flex-row">
                {["Rank", "User", "Invite", "XP"].map((e, i) => {
                  return (
                    <div key={i} className="flex-1 line">
                      {[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1].map((_, id) => {
                        return (
                          <p key={id} className="text-2xl text-center line-i">
                            {e}
                          </p>
                        );
                      })}
                    </div>
                  );
                })}
              </div>
              <p className="more text-center text-2xl">MORE ……</p>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
